# Generated by Django 5.1.3 on 2026-05-24 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('vpn_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('probe_method', models.CharField(choices=[('icmp', 'ICMP ping'), ('tcp', 'TCP connect'), ('http', 'HTTP GET')], default='icmp', max_length=10)),
                ('probe_port', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_state', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('last_response_ms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UptimeDailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('samples_total', models.IntegerField()),
                ('samples_online', models.IntegerField()),
                ('uptime_seconds', models.IntegerField()),
                ('longest_outage_seconds', models.IntegerField()),
                ('agv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='core.agv')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('agv', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UptimeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_online', models.BooleanField()),
                ('response_ms', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('probe', 'probe'), ('heartbeat', 'heartbeat')], default='probe', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('agv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.agv')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agv', 'timestamp'], name='core_uptime_agv_id_37be9e_idx')],
            },
        ),
    ]
